name: Code Quality Checks

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  lint_and_duplication:
    runs-on: ubuntu-latest
    name: Lint & Duplication Check (Java 21)
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Run pmd and Checkstyle
        run: mvn verify
      - name: Run PMD CPD
        run: mvn pmd:cpd-check
      - name: Upload PMD report
        uses: actions/upload-artifact@v4
        with:
          name: pmd-report
          path: target/pmd.xml
      - name: Upload Checkstyle report
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-result
          path: target/checkstyle-result.xml
      - name: Upload CPD report
        uses: actions/upload-artifact@v4
        with:
          name: cpd-report
          path: target/cpd.xml
      - name: Display PMD report
        run: cat target/pmd.xml
      - name: Display CPD report
        run: cat target/cpd.xml
