name: Code Coverage

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  test-coverage:
    needs: Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and test with coverage
        run: mvn clean verify jacoco:report

      - name: Display coverage summary
        run: |
          if [ -f target/site/jacoco/index.html ]; then
            echo "JaCoCo HTML report generated at target/site/jacoco/index.html"
          fi
          if [ -f target/site/jacoco/jacoco.xml ]; then
            echo "JaCoCo XML report generated at target/site/jacoco/jacoco.xml"
          fi

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: |
            target/site/jacoco/index.html
            target/site/jacoco/jacoco.xml
