name: Code Quality Checks

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  lint_and_duplication:
    runs-on: ubuntu-latest
    name: Lint & Duplication Check (Java 21)
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Run Checkstyle
        run: mvn checkstyle:check
      - name: Run PMD CPD
        run: mvn pmd:cpd-check